name: Application Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish -c release

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: Application
        path: bin/release/net6.0/win-x64/publish/Poccy.exe
        retention-days: 1

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
            bin/release/net6.0/win-x64/publish/Poccy.exe

    # No tests to run currently 
    # - name: Test
    # run: dotnet test --no-build --verbosity normal
